openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: https://localhost:3000
    description: Local development servers
  - url: https://task-api-dkq3.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    get:
      summary: List all tasks
      tags:
        - Tasks
      parameters:
        - name: completed
          in: query
          required: false
          description: Filter tasks by completion status
          schema:
            type: boolean
            example: true
        - name: limit
          in: query
          required: false
          description: Maximum number of tasks to return
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
  /tasks/{id}:
    get:
      summary: returns 1 task by id
      tags:
        - Tasks
      parameters:
        - name: completed
          in: path
          required: true
          description: Id of task to select
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          readOnly: true
          type: int
          example: 1
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
  responses:
    BadRequest:
      description: Invalid input
      content:
        applications/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    NotFoundError:
      content:
        applications/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Task not found
